require('dotenv').config({ path: require('path').join(__dirname, '../.env') });
const db = require('./database');

const titles = [
    // Anime 
    { name: 'Naruto', type: 'Anime', genre: 'Action', release_year: 2002 },
    { name: 'Naruto: Shippuden', type: 'Anime', genre: 'Action', release_year: 2007 },
    { name: 'One Piece', type: 'Anime', genre: 'Adventure', release_year: 1999 },
    { name: 'Bleach', type: 'Anime', genre: 'Action', release_year: 2004 },
    { name: 'Dragon Ball Z', type: 'Anime', genre: 'Action', release_year: 1989 },
    { name: 'Dragon Ball', type: 'Anime', genre: 'Adventure', release_year: 1986 },
    { name: 'Attack on Titan', type: 'Anime', genre: 'Action', release_year: 2013 },
    { name: 'Demon Slayer: Kimetsu no Yaiba', type: 'Anime', genre: 'Action', release_year: 2019 },
    { name: 'My Hero Academia', type: 'Anime', genre: 'Action', release_year: 2016 },
    { name: 'Fullmetal Alchemist: Brotherhood', type: 'Anime', genre: 'Adventure', release_year: 2009 },
    { name: 'Fullmetal Alchemist', type: 'Anime', genre: 'Adventure', release_year: 2003 },
    { name: 'Death Note', type: 'Anime', genre: 'Thriller', release_year: 2006 },
    { name: 'Hunter x Hunter', type: 'Anime', genre: 'Action', release_year: 2011 },
    { name: 'Sword Art Online', type: 'Anime', genre: 'Isekai', release_year: 2012 },
    { name: 'Sword Art Online: Alicization', type: 'Anime', genre: 'Isekai', release_year: 2018 },
    { name: 'Tokyo Ghoul', type: 'Anime', genre: 'Horror', release_year: 2014 },
    { name: 'Fairy Tail', type: 'Anime', genre: 'Fantasy', release_year: 2009 },
    { name: 'Black Clover', type: 'Anime', genre: 'Fantasy', release_year: 2017 },
    { name: 'Jujutsu Kaisen', type: 'Anime', genre: 'Action', release_year: 2020 },
    { name: 'Vinland Saga', type: 'Anime', genre: 'Drama', release_year: 2019 },
    { name: 'Re:Zero', type: 'Anime', genre: 'Isekai', release_year: 2016 },
    { name: 'Overlord', type: 'Anime', genre: 'Isekai', release_year: 2015 },
    { name: 'That Time I Got Reincarnated as a Slime', type: 'Anime', genre: 'Isekai', release_year: 2018 },
    { name: 'Steins;Gate', type: 'Anime', genre: 'Sci-Fi', release_year: 2011 },
    { name: 'Code Geass', type: 'Anime', genre: 'Mecha', release_year: 2006 },
    { name: 'Neon Genesis Evangelion', type: 'Anime', genre: 'Mecha', release_year: 1995 },
    { name: 'Gurren Lagann', type: 'Anime', genre: 'Mecha', release_year: 2007 },
    { name: 'Cowboy Bebop', type: 'Anime', genre: 'Sci-Fi', release_year: 1998 },
    { name: 'Trigun', type: 'Anime', genre: 'Action', release_year: 1998 },
    { name: 'Inuyasha', type: 'Anime', genre: 'Fantasy', release_year: 2000 },
    { name: 'Sailor Moon', type: 'Anime', genre: 'Magical Girl', release_year: 1992 },
    { name: 'Yu Yu Hakusho', type: 'Anime', genre: 'Action', release_year: 1992 },
    { name: 'One Punch Man', type: 'Anime', genre: 'Comedy', release_year: 2015 },
    { name: 'Mob Psycho 100', type: 'Anime', genre: 'Comedy', release_year: 2016 },
    { name: 'Haikyuu!!', type: 'Anime', genre: 'Sports', release_year: 2014 },
    { name: "Kuroko's Basketball", type: 'Anime', genre: 'Sports', release_year: 2012 },
    { name: 'Slam Dunk', type: 'Anime', genre: 'Sports', release_year: 1993 },
    { name: 'Clannad', type: 'Anime', genre: 'Romance', release_year: 2007 },
    { name: 'Your Lie in April', type: 'Anime', genre: 'Romance', release_year: 2014 },
    { name: 'Toradora', type: 'Anime', genre: 'Romance', release_year: 2008 },
    { name: 'No Game No Life', type: 'Anime', genre: 'Isekai', release_year: 2014 },
    { name: 'Konosuba', type: 'Anime', genre: 'Isekai', release_year: 2016 },
    { name: 'The Rising of the Shield Hero', type: 'Anime', genre: 'Isekai', release_year: 2019 },
    { name: 'Black Butler', type: 'Anime', genre: 'Mystery', release_year: 2008 },
    { name: 'Ouran High School Host Club', type: 'Anime', genre: 'Romance', release_year: 2006 },
    { name: 'Fruits Basket', type: 'Anime', genre: 'Romance', release_year: 2019 },
    { name: 'Violet Evergarden', type: 'Anime', genre: 'Drama', release_year: 2018 },
    { name: 'Made in Abyss', type: 'Anime', genre: 'Adventure', release_year: 2017 },
    { name: 'Parasyte: The Maxim', type: 'Anime', genre: 'Horror', release_year: 2014 },
    { name: 'Noragami', type: 'Anime', genre: 'Supernatural', release_year: 2014 },
    { name: 'Blue Exorcist', type: 'Anime', genre: 'Supernatural', release_year: 2011 },
    { name: 'Soul Eater', type: 'Anime', genre: 'Action', release_year: 2008 },
    { name: 'The Promised Neverland', type: 'Anime', genre: 'Thriller', release_year: 2019 },
    { name: 'Dr. Stone', type: 'Anime', genre: 'Sci-Fi', release_year: 2019 },
    { name: 'Fire Force', type: 'Anime', genre: 'Action', release_year: 2019 },
    { name: 'Chainsaw Man', type: 'Anime', genre: 'Action', release_year: 2022 },
    { name: 'Spy x Family', type: 'Anime', genre: 'Comedy', release_year: 2022 },
    { name: 'Bleach: Thousand-Year Blood War', type: 'Anime', genre: 'Action', release_year: 2022 },
    { name: 'Tokyo Revengers', type: 'Anime', genre: 'Action', release_year: 2021 },
    { name: 'Berserk', type: 'Anime', genre: 'Action', release_year: 1997 },
    { name: 'Akame ga Kill', type: 'Anime', genre: 'Action', release_year: 2014 },
    { name: 'Seven Deadly Sins', type: 'Anime', genre: 'Fantasy', release_year: 2014 },
    { name: 'Assassination Classroom', type: 'Anime', genre: 'Comedy', release_year: 2015 },
    { name: 'Angel Beats!', type: 'Anime', genre: 'Drama', release_year: 2010 },
    { name: 'Anohana', type: 'Anime', genre: 'Drama', release_year: 2011 },
    { name: 'Oregairu', type: 'Anime', genre: 'Romance', release_year: 2013 },
    { name: 'Food Wars: Shokugeki no Soma', type: 'Anime', genre: 'Comedy', release_year: 2015 },
    { name: 'Gintama', type: 'Anime', genre: 'Comedy', release_year: 2006 },
    { name: "JoJo's Bizarre Adventure", type: 'Anime', genre: 'Action', release_year: 2012 },
    { name: 'Golden Kamuy', type: 'Anime', genre: 'Adventure', release_year: 2018 },
    { name: 'Log Horizon', type: 'Anime', genre: 'Isekai', release_year: 2013 },
    { name: 'Claymore', type: 'Anime', genre: 'Action', release_year: 2007 },
    { name: 'Quintessential Quintuplets', type: 'Anime', genre: 'Romance', release_year: 2019 },
    { name: 'Rent-a-Girlfriend', type: 'Anime', genre: 'Romance', release_year: 2020 },
    { name: 'Plastic Memories', type: 'Anime', genre: 'Romance', release_year: 2015 },
    { name: 'Charlotte', type: 'Anime', genre: 'Supernatural', release_year: 2015 },
    { name: 'Sword Art Online: Progressive', type: 'Anime', genre: 'Isekai', release_year: 2021 },

    // Manga 
    { name: 'Berserk', type: 'Manga', genre: 'Action', release_year: 1989 },
    { name: 'Vagabond', type: 'Manga', genre: 'Drama', release_year: 1998 },
    { name: 'Baki the Grappler', type: 'Manga', genre: 'Action', release_year: 1991 },
    { name: 'One Piece', type: 'Manga', genre: 'Adventure', release_year: 1997 },
    { name: 'Naruto', type: 'Manga', genre: 'Action', release_year: 1999 },
    { name: 'Bleach', type: 'Manga', genre: 'Action', release_year: 2001 },
    { name: 'Attack on Titan', type: 'Manga', genre: 'Action', release_year: 2009 },
    { name: 'Demon Slayer', type: 'Manga', genre: 'Action', release_year: 2016 },
    { name: 'My Hero Academia', type: 'Manga', genre: 'Action', release_year: 2014 },
    { name: 'Jujutsu Kaisen', type: 'Manga', genre: 'Action', release_year: 2018 },
    { name: 'Chainsaw Man', type: 'Manga', genre: 'Action', release_year: 2018 },
    { name: 'Spy x Family', type: 'Manga', genre: 'Comedy', release_year: 2019 },
    { name: 'Vinland Saga', type: 'Manga', genre: 'Drama', release_year: 2005 },
    { name: 'Tokyo Ghoul', type: 'Manga', genre: 'Horror', release_year: 2011 },
    { name: 'Fullmetal Alchemist', type: 'Manga', genre: 'Adventure', release_year: 2001 },
    { name: 'Hunter x Hunter', type: 'Manga', genre: 'Action', release_year: 1998 },
    { name: 'Dragon Ball', type: 'Manga', genre: 'Action', release_year: 1984 },
    { name: 'Death Note', type: 'Manga', genre: 'Thriller', release_year: 2003 },
    { name: 'Haikyuu!!', type: 'Manga', genre: 'Sports', release_year: 2012 },
    { name: 'Black Clover', type: 'Manga', genre: 'Fantasy', release_year: 2015 },

    // Movies
    { name: 'Your Name', type: 'Movie', genre: 'Romance', release_year: 2016 },
    { name: 'Spirited Away', type: 'Movie', genre: 'Fantasy', release_year: 2001 },
    { name: 'Princess Mononoke', type: 'Movie', genre: 'Fantasy', release_year: 1997 },
    { name: "Howl's Moving Castle", type: 'Movie', genre: 'Fantasy', release_year: 2004 },
    { name: 'A Silent Voice', type: 'Movie', genre: 'Drama', release_year: 2016 },
    { name: 'My Neighbor Totoro', type: 'Movie', genre: 'Fantasy', release_year: 1988 },
    { name: 'Akira', type: 'Movie', genre: 'Sci-Fi', release_year: 1988 },
    { name: 'Ghost in the Shell', type: 'Movie', genre: 'Sci-Fi', release_year: 1995 },
    { name: 'Grave of the Fireflies', type: 'Movie', genre: 'Drama', release_year: 1988 },
    { name: 'Wolf Children', type: 'Movie', genre: 'Fantasy', release_year: 2012 },
    { name: 'The Girl Who Leapt Through Time', type: 'Movie', genre: 'Sci-Fi', release_year: 2006 },
    { name: 'Demon Slayer: Mugen Train', type: 'Movie', genre: 'Action', release_year: 2020 },
    { name: 'Dragon Ball Super: Broly', type: 'Movie', genre: 'Action', release_year: 2018 },
    { name: 'One Piece Film: Red', type: 'Movie', genre: 'Adventure', release_year: 2022 },
    { name: 'My Hero Academia: Heroes Rising', type: 'Movie', genre: 'Action', release_year: 2019 },
    { name: 'Jujutsu Kaisen 0', type: 'Movie', genre: 'Action', release_year: 2021 },
    { name: 'Nausicaä of the Valley of the Wind', type: 'Movie', genre: 'Fantasy', release_year: 1984 },
    { name: 'Castle in the Sky', type: 'Movie', genre: 'Adventure', release_year: 1986 },
    { name: "Kiki's Delivery Service", type: 'Movie', genre: 'Fantasy', release_year: 1989 },
    { name: 'The Wind Rises', type: 'Movie', genre: 'Drama', release_year: 2013 },
    { name: 'Belle', type: 'Movie', genre: 'Fantasy', release_year: 2021 },
    { name: 'Weathering With You', type: 'Movie', genre: 'Romance', release_year: 2019 },
    { name: 'The Tale of Princess Kaguya', type: 'Movie', genre: 'Fantasy', release_year: 2013 },
    { name: 'When Marnie Was There', type: 'Movie', genre: 'Drama', release_year: 2014 },
    { name: 'Porco Rosso', type: 'Movie', genre: 'Adventure', release_year: 1992 },
];

// Wipe existing seed data and re insert cleanly
const insertTitle = db.prepare(`
  INSERT INTO titles (name, type, genre, release_year)
  VALUES (@name, @type, @genre, @release_year)
`);

const seedAll = db.transaction((titles) => {
    db.prepare('DELETE FROM titles').run();
    for (const title of titles) insertTitle.run(title);
});

seedAll(titles);
console.log(` Seeded ${titles.length} titles into the database.`);